import type { Metadata } from "next";
import localFont from "next/font/local";
import NavBar from "@/components/NavBar";
import "./globals.css";
import Providers from "./providers";
import React from "react";
import {Button} from "@nextui-org/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        
        <NavBar/>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
